    create table Bus (
        id bigint generated by default as identity,
        acAvailable boolean not null,
        buyingPrice bigint,
        engineCapacity bigint,
        modelNo varchar(255),
        seatCount integer not null,
        primary key (id)
    ); 
    create table SaleTransaction (
        Id bigint generated by default as identity,
        saleDate timestamp,
        salePrice bigint,
        vehicleType varchar(255),
        vehicleId bigint,
        primary key (Id)
    ); 
    create table Truck (
        id bigint generated by default as identity,
        buyingPrice bigint,
        engineCapacity bigint,
        modelNo varchar(255),
        trunkVolumeCapacity bigint,
        primary key (id)
    );